'use strict';
const crypto = require('node:crypto');
const { put, del } = require('@vercel/blob');
const { ensureSchema, sqlClient, mapPost } = require('./lib/db');
const { json, sameOrigin, body, text, slugify, safeUrl, sanitizeContent, SITE_URL } = require('./lib/core');
const { issueSession, clearSession, session, requireAdmin, bootstrapAdmin, verifyPassword } = require('./lib/auth');
const allowedImages = new Set(['image/jpeg','image/png','image/webp','image/gif']);
function validImageBytes(buffer,mime){ if(mime==='image/jpeg') return buffer[0]===0xff&&buffer[1]===0xd8&&buffer[2]===0xff; if(mime==='image/png') return buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])); if(mime==='image/gif') return ['GIF87a','GIF89a'].includes(buffer.subarray(0,6).toString('ascii')); if(mime==='image/webp') return buffer.subarray(0,4).toString('ascii')==='RIFF'&&buffer.subarray(8,12).toString('ascii')==='WEBP'; return false; }
function normalize(input, existing={}) { const title=text(input.title||existing.title,180); const slug=slugify(input.slug||existing.slug||title); const status=input.status==='published'?'published':'draft'; const contentHtml=sanitizeContent(input.contentHtml||existing.contentHtml||''); if(!title||!slug||!contentHtml) throw Object.assign(new Error('Title, slug and article content are required.'),{status:400}); const featuredImage=text(input.featuredImage||existing.featuredImage,2000); if(featuredImage&&!/^https:\/\//.test(featuredImage)&&!/^assets\/blog\//.test(featuredImage)) throw Object.assign(new Error('Featured image URL is invalid.'),{status:400}); return {id:existing.id||crypto.randomUUID(),title,slug,excerpt:text(input.excerpt||existing.excerpt,500),contentHtml,featuredImage,imageAlt:text(input.imageAlt||existing.imageAlt,180),category:text(input.category||existing.category,80)||'Journal',tags:[...new Set((Array.isArray(input.tags)?input.tags:existing.tags||[]).map(v=>text(v,40)).filter(Boolean))].slice(0,12),author:text(input.author||existing.author,100)||'Ritesh Singh',status,seoTitle:text(input.seoTitle||title,180),metaDescription:text(input.metaDescription||input.excerpt||existing.metaDescription,320),focusKeyword:text(input.focusKeyword||existing.focusKeyword,100),canonical:safeUrl(input.canonical,`${SITE_URL}/blog/${slug}`)}; }
module.exports = async (req,res) => { try { if(!sameOrigin(req)) return json(res,403,{error:'Origin rejected.'}); await bootstrapAdmin(); const path=String(req.query?.path||'').replace(/^\/+|\/+$/g,''); const sql=sqlClient();
  if(path==='login'&&req.method==='POST'){ const input=body(req), email=text(input.email,200).toLowerCase(); const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0]; const ipHash=crypto.createHash('sha256').update(`${process.env.AUTH_SECRET}:${ip}`).digest('hex'); const attempts=await sql.query(`SELECT COUNT(*)::int AS count FROM login_events WHERE ip_hash=$1 AND created_at>NOW()-INTERVAL '15 minutes'`,[ipHash]); if(attempts[0].count>=8) return json(res,429,{error:'Too many login attempts. Try again later.'}); const rows=await sql.query('SELECT * FROM users WHERE email=$1 LIMIT 1',[email]); if(!rows[0]||!verifyPassword(input.password,rows[0].password_hash)){ await sql.query('INSERT INTO login_events (id,ip_hash) VALUES ($1,$2)',[crypto.randomUUID(),ipHash]); return json(res,401,{error:'Invalid email or password.'}); } await sql.query('DELETE FROM login_events WHERE ip_hash=$1',[ipHash]); const auth=issueSession(res,rows[0]); return json(res,200,{user:{email:rows[0].email},csrfToken:auth.csrf}); }
  if(path==='logout'&&req.method==='POST'){ requireAdmin(req,{csrf:true}); clearSession(res); return json(res,200,{ok:true}); }
  if(path==='session'&&req.method==='GET'){ const auth=session(req); return auth?json(res,200,{authenticated:true,user:{email:auth.email},csrfToken:auth.csrf}):json(res,401,{error:'Authentication required.'}); }
  requireAdmin(req,{csrf:req.method!=='GET'});
  if(path==='posts'&&req.method==='GET'){ const rows=await sql.query('SELECT * FROM blog_posts ORDER BY updated_at DESC'); return json(res,200,{posts:rows.map(mapPost)}); }
  if(path==='posts'&&req.method==='POST'){ const post=normalize(body(req)); const rows=await sql.query(`INSERT INTO blog_posts (id,title,slug,excerpt,content_html,featured_image,image_alt,category,tags,author,status,seo_title,meta_description,focus_keyword,canonical_url,published_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11,$12,$13,$14,$15,CASE WHEN $11='published' THEN NOW() ELSE NULL END) RETURNING *`,[post.id,post.title,post.slug,post.excerpt,post.contentHtml,post.featuredImage,post.imageAlt,post.category,JSON.stringify(post.tags),post.author,post.status,post.seoTitle,post.metaDescription,post.focusKeyword,post.canonical]); return json(res,201,{post:mapPost(rows[0])}); }
  const match=path.match(/^posts\/(.+)$/); if(match){ const oldSlug=decodeURIComponent(match[1]); const found=await sql.query('SELECT * FROM blog_posts WHERE slug=$1 LIMIT 1',[oldSlug]); if(!found[0]) return json(res,404,{error:'Post not found.'}); if(req.method==='DELETE'){ await sql.query('DELETE FROM blog_posts WHERE id=$1',[found[0].id]); return json(res,200,{ok:true}); } if(req.method==='PUT'){ const post=normalize(body(req),mapPost(found[0])); const rows=await sql.query(`UPDATE blog_posts SET title=$2,slug=$3,excerpt=$4,content_html=$5,featured_image=$6,image_alt=$7,category=$8,tags=$9::jsonb,author=$10,status=$11,seo_title=$12,meta_description=$13,focus_keyword=$14,canonical_url=$15,updated_at=NOW(),published_at=CASE WHEN $11='published' THEN COALESCE(published_at,NOW()) ELSE NULL END WHERE id=$1 RETURNING *`,[found[0].id,post.title,post.slug,post.excerpt,post.contentHtml,post.featuredImage,post.imageAlt,post.category,JSON.stringify(post.tags),post.author,post.status,post.seoTitle,post.metaDescription,post.focusKeyword,post.canonical]); return json(res,200,{post:mapPost(rows[0])}); } }
  if(path==='upload'&&req.method==='POST'){ const input=body(req), mime=text(input.mime,100); if(!allowedImages.has(mime)) return json(res,415,{error:'Only JPEG, PNG, WebP and GIF images are allowed.'}); const match=String(input.data||'').match(/^data:[^;]+;base64,(.+)$/); if(!match) return json(res,400,{error:'Invalid image data.'}); const buffer=Buffer.from(match[1],'base64'); if(!buffer.length||buffer.length>3*1024*1024) return json(res,413,{error:'Image must be smaller than 3 MB.'}); if(!validImageBytes(buffer,mime)) return json(res,415,{error:'The file contents do not match a supported image format.'}); const filename=slugify(String(input.filename||'image').replace(/\.[^.]+$/,''))||'image'; const ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/gif":"gif"}[mime]; const blob=await put(`blog/${filename}.${ext}`,buffer,{access:'public',addRandomSuffix:true,contentType:mime,token:process.env.BLOB_READ_WRITE_TOKEN}); await sql.query('INSERT INTO media (id,url,pathname,filename,mime_type,size_bytes) VALUES ($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),blob.url,blob.pathname,String(input.filename||filename),mime,buffer.length]); return json(res,201,{url:blob.url}); }
  if(path==='media'&&req.method==='GET'){ const rows=await sql.query('SELECT * FROM media ORDER BY created_at DESC'); return json(res,200,{media:rows}); }
  if(path.startsWith('media/')&&req.method==='DELETE'){ const id=decodeURIComponent(path.slice(6)); const rows=await sql.query('DELETE FROM media WHERE id=$1 RETURNING url',[id]); if(rows[0]) await del(rows[0].url,{token:process.env.BLOB_READ_WRITE_TOKEN}); return json(res,200,{ok:true}); }
  if(path==='categories'&&req.method==='GET'){ const rows=await sql.query(`SELECT category, COUNT(*)::int AS count FROM blog_posts GROUP BY category ORDER BY category`); return json(res,200,{categories:rows}); }
  return json(res,404,{error:'API route not found.'});
 } catch(error){ if(error.code==='23505') return json(res,409,{error:'That slug or record already exists.'}); return json(res,error.status||500,{error:error.status?error.message:'The server could not complete this request.'}); } };
